### ISSUE TITLE
this could well be a vmod

### ISSUE THREAD

**Issue by ibotty** [cosimo/varnish-accept-language#3]
are there plans to modify it to be a vmod?

**Comment by cosimo** [comment]
yes, there is a plan to do that. For now, we're running on 2.[01], so it's not strictly necessary.

**Comment by arthurzenika** [comment]
+1 on this issue.

**Comment by arthurzenika** [comment]
Any news on this ? Or an equivalent that could be used in the existing vmods : https://www.varnish-cache.org/vmods ? We're planning to migrate to wheezy so varnish3 will be the new version in use.

**Comment by oppianmatt** [comment]
Is this project still used? Is there a vmod now? varnish4 is out

**Comment by cosimo** [comment]
Yes, this project is still used in production in many places.
Yes, a VMOD of it is being worked on as well: https://github.com/cosimo/libvmod-i18n
